# Custom costs for character-level operations relfecting Spanish spelling conventions.
# First key is the operation type: "sub" for substitution, "ins" for insertion, and "del" for deletion.
# Second key is a tuple of characters representing the unit being operated on.
# Substitution values are lists of (second_unit, cost) pairs, 
#   where second_unit is a tuple of characters representing the other unit involved in the substitution.
#   Substitution costs are stored one-way for brevity, but the add_inverse_subs function adds the corresponding inverse mappings automatically.
# Insertion and deletion values are single costs.
_CHAR_COSTS_ONE_WAY = {
    "sub": {
        # diacritic substitutions
        ("a",): [(("á",), 0.10), (("ä",), 0.25)],
        ("e",): [(("é",), 0.10)],
        ("i",): [(("í",), 0.10), (("y",), 0.50)],
        ("o",): [(("ó",), 0.10), (("ö",), 0.25)],
        ("u",): [(("ú",), 0.10), (("ü",), 0.25), (("v",), 0.50)],
        ("n",): [(("ñ",), 0.25)],
        ("y",): [(("ÿ",), 0.25)],
        # phonetic substitutions
        ("b",):    [(("v",), 0.50)],
        ("c",):    [(("s",), 0.50), (("z",), 0.50), (("q",), 0.50)],
        ("s",):    [(("z",), 0.50)],
        ("g",):    [(("j",), 0.50)],
        ("p", "h"): [(("f",), 0.50)],
    },
    # silent 'h' insertion and deletion
    "ins": {("h",): 0.50},
    "del": {("h",): 0.50},
}

# Custom costs for token-level operations reflecting Spanish name usage conventions.
# First key is the operation type: "sub" for substitution, "ins" for insertion, and "del" for deletion.
# Second key is a tuple of tokens representing the unit being operated on.
# Substitution values are lists of (second_unit, cost) pairs,
#   where second_unit is a tuple of tokens representing the other unit involved in the substitution.
#   Substitution costs are stored one-way for brevity, but the add_inverse_subs function adds the corresponding inverse mappings automatically.
# Insertion and deletion values are single costs.
_TOKEN_COSTS_ONE_WAY = {
    "sub": {
        # masculine nicknames and english equivalent substitutions
        ("beto",):         [(("alberto",), 0.15), (("roberto",), 0.15), (("albert",), 0.25), (("robert",), 0.25)],
        ("alberto",):      [(("albert",), 0.15)],
        ("roberto",):      [(("robert",), 0.15)],
        ("pancho",):       [(("francisco",), 0.15), (("francis",), 0.25)],
        ("paco",):         [(("francisco",), 0.15), (("francis",), 0.25)],
        ("francisco",):    [(("francis",), 0.15)],
        ("chofo",):        [(("rodolfo",), 0.15), (("rudolph",), 0.25)],
        ("rodolfo",):      [(("rudolph",), 0.15)],
        ("chepe",):        [(("josé",), 0.15), (("joseph",), 0.25)],
        ("pepe",):         [(("josé",), 0.15), (("joseph",), 0.25)],
        ("josé",):         [(("joseph",), 0.15)],
        ("meme",):         [(("manuel",), 0.15)],
        ("manuel",):       [(("manola",), 0.15), (("manolo",), 0.15)],
        ("alejo",):        [(("alejandro",), 0.15), (("alexander",), 0.25)],
        ("fonsi",):        [(("alfonso",), 0.15), (("alphonse",), 0.25)],
        ("poncho",):       [(("alfonso",), 0.15), (("alphonse",), 0.25)],
        ("jano",):         [(("alejandro",), 0.15), (("alexander",), 0.25)],
        ("alejandro",):    [(("alexander",), 0.15)],
        ("chejo",):        [(("sergio",), 0.15)],
        ("chus",):         [(("jesús",), 0.15)],
        ("chuy",):         [(("jesús",), 0.15)],
        ("adi",):          [(("adolfo",), 0.15), (("adolph",), 0.25)],
        ("adolfo",):       [(("adolph",), 0.15)],
        ("güicho",):       [(("luis",), 0.15), (("louis",), 0.25)],
        ("lucho",):        [(("luis",), 0.15), (("louis",), 0.25)],
        ("luis",):         [(("louis",), 0.15), (("louise",), 0.15)],
        ("chente",):       [(("vicente",), 0.15), (("vincent",), 0.25)],
        ("vicente",):      [(("vincent",), 0.15)],
        ("kiko",):         [(("federico",), 0.15), (("frederick",), 0.25)],
        ("federico",):     [(("frederick",), 0.15)],
        ("lalo",):         [(("eduardo",), 0.15), (("edward",), 0.25)],
        ("eduardo",):      [(("edward",), 0.15)],
        ("lencho",):       [(("lorenzo",), 0.15), (("lawrence",), 0.25)],
        ("lorenzo",):      [(("lawrence",), 0.15)],
        ("memo",):         [(("guillermo",), 0.15), (("william",), 0.25)],
        ("guillermo",):    [(("william",), 0.15)],
        ("mingo",):        [(("domingo",), 0.15), (("dominic",), 0.25)],
        ("domingo",):      [(("dominic",), 0.15)],
        ("neto",):         [(("ernesto",), 0.15), (("earnest",), 0.25)],
        ("ernesto",):      [(("earnest",), 0.15)],
        ("nando",):        [(("fernando",), 0.15), (("ferdinand",), 0.25)],
        ("fernando",):     [(("ferdinand",), 0.15)],
        ("monchi",):       [(("ramón",), 0.15), (("raymond",), 0.25)],
        ("ramón",):        [(("raymond",), 0.15)],
        ("rulo",):         [(("raúl",), 0.15)],
        ("nacho",):        [(("ignacio",), 0.15), (("ignatius",), 0.25)],
        ("nancho",):       [(("ignacio",), 0.15), (("ignatius",), 0.25)],
        ("ignacio",):      [(("ignatius",), 0.15)],
        ("toño",):         [(("antonio",), 0.15), (("anthony",), 0.25)],
        ("antonio",):      [(("anthony",), 0.15)],
        ("quique",):       [(("enrique",), 0.15), (("henry",), 0.25)],
        ("enrique",):      [(("henry",), 0.15)],
        ("goyo",):         [(("gregorio",), 0.15), (("gregory",), 0.25)],
        ("gregorio",):     [(("gregory",), 0.15)],
        ("miguel",):       [(("michael",), 0.15)],
        ("juan",):         [(("john",), 0.15)],
        ("pablo",):        [(("paul",), 0.15)],
        ("adán",):         [(("adam",), 0.15)],
        ("agustín",):      [(("augustine",), 0.15)],
        ("alfonso",):      [(("alfonse",), 0.15), (("alonso",), 0.15)],
        ("alfonse",):      [(("alonso",), 0.15)],
        ("alfredo",):      [(("alfred",), 0.15)],
        ("ambrosio",):     [(("ambrose",), 0.15)],
        ("andrés",):       [(("andrew",), 0.15)],
        ("armando",):      [(("herman",), 0.15)],
        ("arturo",):       [(("arthur",), 0.15)],
        ("bartolomé",):    [(("bartholomew",), 0.15)],
        ("bautista",):     [(("baptiste",), 0.15)],
        ("benito",):       [(("benedict",), 0.15)],
        ("bernardino",):   [(("bernardo",), 0.15)],
        ("bruno",):        [(("brown",), 0.15)],
        ("buenaventura",): [(("bonaventura",), 0.15)],
        ("carlos",):       [(("charles",), 0.15)],
        ("cornelio",):     [(("cornelius",), 0.15)],
        ("cristián",):     [(("christian",), 0.15)],
        ("cristóbal",):    [(("christopher",), 0.15)],
        ("darío",):        [(("darius",), 0.15)],
        ("desi",):         [(("desiderio",), 0.15)],
        ("diego",):        [(("santiago",), 0.15)],
        ("edgardo",):      [(("edgar",), 0.15)],
        ("edmundo",):      [(("edmund",), 0.15)],
        ("emilio",):       [(("emile",), 0.15)],
        ("esteban",):      [(("stephen",), 0.15)],
        ("eusebio",):      [(("eusebius",), 0.15)],
        ("fabio",):        [(("fabius",), 0.15)],
        ("fabricio",):     [(("fabrice",), 0.15)],
        ("felipe",):       [(("philip",), 0.15)],
        ("félix",):        [(("felix",), 0.15)],
        ("fermin",):       [(("firmin",), 0.15)],
        ("geraldo",):      [(("gerald",), 0.15)],
        ("gerardo",):      [(("gerard",), 0.15)],
        ("gustavo",):      [(("gustav",), 0.15)],
        ("herberto",):     [(("herbert",), 0.15)],
        ("hernán",):       [(("hernando",), 0.15)],
        ("hugo",):         [(("hugh",), 0.15)],
        ("jacobo",):       [(("jacob",), 0.15)],
        ("jaime",):        [(("james",), 0.15)],
        ("javier",):       [(("xavier",), 0.15)],
        ("jerónimo",):     [(("jerome",), 0.15)],
        ("joaquín",):      [(("joachim",), 0.15), (("joachin",), 0.15)],
        ("jorge",):        [(("george",), 0.15)],
        ("josue",):        [(("joshua",), 0.15)],
        ("julio",):        [(("julius",), 0.15)],
        ("leonardo",):     [(("leonard",), 0.15)],
        ("leopoldo",):     [(("leopold",), 0.15)],
        ("luciano",):      [(("lucian",), 0.15)],
        ("marcelo",):      [(("marcellus",), 0.15)],
        ("marcio",):       [(("marcus",), 0.15)],
        ("marco",):        [(("mark",), 0.15)],
        ("mateo",):        [(("matthew",), 0.15)],
        ("matías",):       [(("matthias",), 0.15)],
        ("maximiliano",):  [(("maximilian",), 0.15)],
        ("máximo",):       [(("maximus",), 0.15)],
        ("agusto",):       [(("agustus",), 0.15)],
        ("heracio",):      [(("hoartio",), 0.15), (("horatius",), 0.15)],
        ("cruz",):         [(("cross",), 0.15), (("cruzita",), 0.15)],
        ("chema",):    [(("josé", "maría"), 0.15), (("joseph", "mary"), 0.15)],
        ("juampa",):   [(("juan", "pablo"), 0.15), (("john", "paul"), 0.15)],
        ("juandi",):   [(("juan", "diego"), 0.15), (("john", "diego"), 0.15)],
        ("juanjo",):   [(("juan", "josé"), 0.15), (("john", "joseph"), 0.15)],
        ("juanfran",): [(("juan", "francisco"), 0.15), (("john", "francis"), 0.15)],
        ("juancho",):  [(("juan", "francisco"), 0.15), (("john", "francis"), 0.15)],
        ("juanfer",):  [(("juan", "fernando"), 0.15), (("john", "ferdinand"), 0.15)],
        ("luismi",):   [(("luis", "miguel"), 0.15), (("louis", "michael"), 0.15)],

        # feminine nicknames and english equivalent substitutions
        ("licha",):      [(("alicia",), 0.15), (("alice",), 0.25)],
        ("alicia",):     [(("alice",), 0.15)],
        ("calu",):       [(("claudia",), 0.15)],
        ("chayo",):      [(("rosario",), 0.15), (("rosary",), 0.25)],
        ("rosario",):    [(("rosary",), 0.15)],
        ("concha",):     [(("concepción",), 0.15), (("conception",), 0.25), (("conchita",), 0.15)],
        ("conchita",):   [(("chita",), 0.15)],
        ("concepción",): [(("conception",), 0.15)],
        ("lena",):       [(("magdalena",), 0.15), (("magdalene",), 0.25)],
        ("magdalena",):  [(("magdalene",), 0.15)],
        ("leti",):       [(("leticia",), 0.15), (("letitia",), 0.25)],
        ("leticia",):    [(("letitia",), 0.15)],
        ("luchi",):      [(("lucía",), 0.15), (("lucy",), 0.25)],
        ("lucía",):      [(("lucy",), 0.15)],
        ("mar",):        [(("mariana",), 0.15), (("marianna",), 0.15), (("maryanne",), 0.25)],
        ("mariana",):    [(("marianna",), 0.15), (("maryanne",), 0.15)],
        ("tita",):       [(("marta",), 0.15), (("martha",), 0.25)],
        ("marta",):      [(("martha",), 0.15)],
        ("meches",):     [(("mercedes",), 0.15)],
        ("pili",):       [(("pilar",), 0.15)],
        ("paquita",):    [(("francisca",), 0.15), (("frances",), 0.25)],
        ("francisca",):  [(("frances",), 0.15)],
        ("pepita",):     [(("josefa",), 0.15), (("josephine",), 0.25)],
        ("josefa",):     [(("josephine",), 0.15)],
        ("tina",):       [(("cristina",), 0.15), (("christine",), 0.25), (("christina",), 0.25)],
        ("cristina",):   [(("christine",), 0.15), (("christina",), 0.15)],
        ("vicky",):      [(("victoria",), 0.15)],
        ("vivi",):       [(("viviana",), 0.15), (("vivianne",), 0.25)],
        ("viviana",):    [(("vivianne",), 0.15)],
        ("geli",):       [(("angélica",), 0.15)],
        ("gela",):       [(("angélica",), 0.15)],
        ("lola",):       [(("dolores",), 0.15)],
        ("fani",):       [(("estefanía",), 0.15), (("stephanie",), 0.25)],
        ("estefanía",):  [(("stephanie",), 0.15)],
        ("lupe",):       [(("guadalupe",), 0.15)],
        ("chavela",):    [(("isabela",), 0.15), (("isabelle",), 0.25)],
        ("isabela",):    [(("isabelle",), 0.15), (("isabel",), 0.15)],
        ("isabelle",):   [(("isabel",), 0.15)],
        ("chío",):       [(("rocío",), 0.15)],
        ("sandy",):      [(("sandra",), 0.15)],
        ("clementina",): [(("cleme",), 0.15)],
        ("maría",):      [(("mary",), 0.15)],
        ("adelita",):    [(("adele",), 0.15)],
        ("alejandra",):  [(("alexandra",), 0.15)],
        ("ana",):        [(("anna",), 0.15)],
        ("anabella",):   [(("annabel",), 0.15)],
        ("antonietta",): [(("antonia",), 0.15)],
        ("anunciación",):[(("annunziata",), 0.15)],
        ("ascención",):  [(("ascension",), 0.15)],
        ("asunción",):   [(("asumption",), 0.15)],
        ("beatriz",):    [(("beatrix",), 0.15)],
        ("blanca",):     [(("blanche",), 0.15)],
        ("camila",):     [(("camilla",), 0.15)],
        ("caridad",):    [(("charity",), 0.15)],
        ("carla",):      [(("carlota",), 0.15)],
        ("carmela",):    [(("carmel",), 0.15)],
        ("carmelita",):  [(("carmel",), 0.15)],
        ("carmen",):     [(("carmel",), 0.15)],
        ("carmina",):    [(("carmel",), 0.15)],
        ("catalina",):   [(("katherine",), 0.15)],
        ("catherina",):  [(("catherine",), 0.15)],
        ("clarisa",):    [(("clarissa",), 0.15)],
        ("constanza",):  [(("constance",), 0.15)],
        ("consuelo",):   [(("consolation",), 0.15)],
        ("débora",):     [(("deborah",), 0.15)],
        ("delfina",):    [(("delphina",), 0.15)],
        ("dominga",):    [(("dominique",), 0.15)],
        ("elena",):      [(("helen",), 0.15), (("ileana",), 0.15)],
        ("eloisa",):     [(("eloise",), 0.15)],
        ("ema",):        [(("emma",), 0.15)],
        ("emilia",):     [(("emily",), 0.15), (("amelia",), 0.15)],
        ("emperatriz",): [(("empress",), 0.15)],
        ("ernesta",):    [(("ernest",), 0.15)],
        ("esmeralda",):  [(("emerald",), 0.15)],
        ("esperanza",):  [(("hope",), 0.15)],
        ("estela",):     [(("estelle",), 0.15), (("star",), 0.15)],
        ("eugenia",):    [(("eugenie",), 0.15)],
        ("evangelina",): [(("evangeline",), 0.15)],
        ("evita",):      [(("eva",), 0.15)],
        ("faustina",):   [(("faustus",), 0.15)],
        ("feliciana",):  [(("feliciano",), 0.15)],
        ("filomena",):   [(("philomena",), 0.15)],
        ("florentina",): [(("florence",), 0.15)],
        ("florinda",):   [(("flora",), 0.15)],
        ("gabriela",):   [(("gabrielle",), 0.15), (("gabriella",), 0.15)],
        ("genoveva",):   [(("genevieve",), 0.15)],
        ("gracia",):     [(("grace",), 0.15)],
        ("hortensia",):  [(("hortense",), 0.15)],
        ("inés",):       [(("agnes",), 0.15)],
        ("inmaculada",): [(("immaculate",), 0.15)],
        ("isidora",):    [(("isidore",), 0.15)],
        ("ivette",):     [(("yvette",), 0.15)],
        ("jacinta",):    [(("hyacinth",), 0.15)],
        ("leonor",):     [(("eleanor",), 0.15)],
        ("lidia",):      [(("lydia",), 0.15)],
        ("liliana",):    [(("lillian",), 0.15)],
        ("lorena",):     [(("lorraine",), 0.15)],
        ("lorenza",):    [(("lauren",), 0.15)],
        ("lucila",):     [(("lucille",), 0.15)],
        ("margarita",):  [(("margaret",), 0.15)],
        ("marita",):     [(("maría",), 0.15)],
        ("matilde",):    [(("matilda",), 0.15)],
        ("mayra",):      [(("myra",), 0.15)],
        ("bethlehem",):  [(("belén",), 0.15)],
        ("alba",):       [(("dawn",), 0.15)],
        ("dawn",):       [(("aurora",), 0.15)],
        ("gloria",):     [(("geoffrey",), 0.15)],
        ("dorothy",):    [(("donato",), 0.15)],
        ("majo",):      [(("maría", "josé"), 0.15), (("mary", "joseph"), 0.15)],
        ("anabel",):    [(("ana", "belen"), 0.15), (("ana", "bethlehem"), 0.15)],
        ("anaisa",):    [(("ana", "isabel"), 0.15), (("ana", "isabelle"), 0.15)],
        ("maribel",):   [(("maría", "isabel"), 0.15), (("mary", "isabelle"), 0.15)],
        ("mabel",):     [(("maría", "isabel"), 0.15), (("mary", "isabelle"), 0.15)],
        ("mafer",):     [(("maría", "fernanda"), 0.15), (("mary", "fernanda"), 0.15)],
        ("mayte",):     [(("maría", "teresa"), 0.15), (("mary", "teresa"), 0.15)],
        ("malena",):    [(("maría", "elena"), 0.15), (("mary", "elena"), 0.15)],
        ("marianela",): [(("maría", "estela"), 0.15)],
        ("marciela",):  [(("maría", "celia"), 0.15)],
        ("maricarmen",):[(("maría", "del", "carmen"), 0.15)],
    },
    "ins": {
        # prepositions and articles insertions
        ("de",):  0.20,
        ("del",): 0.20,
        ("la",):  0.10,
        ("los",): 0.10,
        ("las",): 0.10,
        # common names insertions
        ("juan",):  0.15,
        ("josé",):  0.15,
        ("maría",): 0.15,
    },
    "del": {
        # prepositions and articles deletions
        ("de",):  0.20,
        ("del",): 0.20,
        ("la",):  0.10,
        ("los",): 0.10,
        ("las",): 0.10,
    },
}

# Default multigraphs and their placeholder characters to be treated as single units in character-level comparisons.
MULTIGRAPH_PLACEHOLDERS: list[tuple[str, str]] = [
    ("rr", "ρ"),
    ("ll", "λ"),
    ("cc", "γ"),
    ("ch", "χ"),
]


def add_inverse_subs(costs: dict):
    """
    Returns a copy of a one-way cost dictionary with inverted substitution pairs added.
    """
    expanded = {op: dict(entries) for op, entries in costs.items()}
    for key, values in costs["sub"].items():
        for value, cost in values:
            if value not in expanded["sub"]:
                expanded["sub"][value] = []
            if not any(existing_key == key for existing_key, _ in expanded["sub"][value]):
                expanded["sub"][value].append((key, cost))
    return expanded


# Expanded cost dictionaries with inverse substitutions included.
CHAR_COSTS: dict = add_inverse_subs(_CHAR_COSTS_ONE_WAY)
TOKEN_COSTS: dict = add_inverse_subs(_TOKEN_COSTS_ONE_WAY)